# Ingress vers la api srv du vcluster
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: vcluster-ingress
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`vcluster-demo.34.160.162.187.sslip.io`)
    services:
    - name: demo
      port: 443
  tls:
    passthrough: true